application: tumgor
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /user.*
  script: user.py

- url: /.*
  script: main.py


error_handlers:
- file: error.html
